### ISSUE TITLE
Links not working in Product Overview section

### ISSUE THREAD

**Issue by fiservakshay** [Fiserv/Support#552]
Hi Team,

I am unable to add hyperlinks in Product Overview Section. All hyperlinks are being displayed as plain text.
Please refer the screenshot below:

![image](https://github.com/Fiserv/Support/assets/81968767/4c8bfb75-35a3-4d61-9259-a126f7ebb986)

Here's the code for your reference:

```
benefits:
  - title: Market Reach
    description: Offer your pre-integrated solution to a market of more than 1 in 3 U.S. financial institutions via <a href="https://appmarket.fiservapps.com/" target="_blank" title="Open link in new tab">AppMarket from Fiserv</a>.
  - title: Simplified Integration.
    description: The [Get Started](?path=docs/getting-started.md) page provides detailed instructions for accessing more than 25,000 fields from Fiserv banking solutions. 
  - title: Co-Innovation
    description: Be <a href="https://www.fiserv.com/en/lp/fintech-collaboration.html?rdf=/collaboration&rdc=2023/10/19&rdr=2024/10/19" title="Open link in new tab">among the first</a> to experience a new fintech collaboration platform that streamlines B2B partnership and co-innovation.  
```
Please suggest how to fix this issue.

cc: @sfiserv
