### ISSUE TITLE
Unhandled Errors (Blank Page) in API Explorer

### ISSUE THREAD

**Issue by KGroninger** [Fiserv/Support#834]
[developer.fiserv.com-1747766921144.log](https://github.com/user-attachments/files/20353843/developer.fiserv.com-1747766921144.log)

https://github.com/user-attachments/assets/8bf3ec42-9120-454a-b362-23e75f55b983

### Product

CardPointe

### Page

https://developer.fiserv.com/product/CardPointe/api/?type=post&path=/api/v3/tip&branch=main&version=1.0.0

### Description

On 5/19, an internal user notified me that when navigating to API Explorer > CardPointe Integrated Terminal API > Tip (https://developer.fiserv.com/product/CardPointe/api/?type=post&path=/api/v3/tip&branch=main&version=1.0.0), and selecting the Request Schema tab, the browser would refresh and display a blank page. See attachment "Tip Request Schema Error Recording."

In experimenting with the schema, I narrowed the issue down to the tipPercentPresets array, and the example field in the spec file, which looked as follows:

```
tipPercentPresets:
  type: array
  example: [10, 12, 20]
  description: |
    <p>An array of three preset tip percentages, in the format <code>[n, n, n]</code>.</p><br>
    <p><strong>Required</strong> if <code>"includeCustomTipAmount":"false"</code>.</p><br>
    <p><em>Note: The ability to set four preset values is planned for a future enhancement.</em></p>
```

I copied this into Swagger UI and noticed that it rendered correctly, but was accompanied by a persistent loading icon, so something had to be off.

Since the spec validator never flagged any issues with this code, I believe this exposes a bug or poor error handling on the Dev Studio front end. 

I grabbed a Chrome Console snippet (see attachment developer.fiserv.com-1747766921144.log), which is the only insight I can find that the front end is experiencing some error.

### Expected Behaviour

Catch spec file errors in the spec file validator. Otherwise, display a meaningful error message in the front end.

### Operating system

macOS Sequoia Version 15.4.1 (24E263)

### Browser

Version 136.0.7103.114 (Official Build) (arm64)

**Comment by KGroninger** [comment]
### Follow-up #1 - I made it worse :) in QA

In experimenting with the tipPercentPresets syntax, I made an update that worked perfectly in Swagger UI, and correct, according to OAPI syntax, but now caused the blank page issue in Dev Studio at the endpoint level, instead of at the Request Schema.

This time, the code was as follows:

```
tipPercentPresets:
  type: array
  items:
    type: integer
    type: number
  example: [10, 12, 20]
  description: |
  <p>An array of three preset tip percentages, in the format <code>[n, n, n].</p>
  <p><strong>Required</strong> if <code>"includeCustomTipAmount":"false"</code>.</p>
  <p><em>Note: The ability to set four preset values is planned for a future enhancement.</em></p></code>
```

Now, just attempting to load the tip endpoint page (https://qa-developer.fiserv.com/product/CardPointe/api/?type=post&path=/api/v3/tip&branch=develop&version=1.0.0) caused the site to refresh and display a blank page. 

Again I grabbed the log from the Console (see attached qa-developer.fiserv.com-1747767558087.log).
